### ISSUE TITLE
1.21 NeoForge on CurseForge showing not download 

### ISSUE THREAD

**Issue by Myphicbowser** [Pandarix/BetterArcheology#100]
On CurseForge, the mod states it supports NeoForge and the latest edition of Minecraft (1.21.1) but it will not let itself be downloaded and states it is not compatible

I know using a ModLoader is kinda lazy, but it makes sure its all installed right so thats my main concern

**Comment by Pandarix** [comment]
This was probably due to an older version of the mod supporting NeoForge since NeoForge and Forge were compatible with eachother until the 1.20.2 (if I'm not mistaken). The mod also supports the 1.21.1 but as of now not NeoForge.
This will change very soon (hopefully this weekend). Then you'll be able to play 1.21.1 on NeoForge :)
