### ISSUE TITLE
Soaring Winds enchantment incompatabilities

### ISSUE THREAD

**Issue by NeedsterW** [Pandarix/BetterArcheology#70]
The Soaring Winds enchantment is incompatible with Tarantula Hawk Elytra from Alex's Mobs

**Comment by Pandarix** [comment]
This is because the Enchantment tests for an ElytraItem. However, the Tarantula Hawk Elytra from Alex's Mobs does not extend the Elytra class. I'll replace that check with something more abstract.

Sorry for the incompatibility. This will be fixed in the next update!

**Comment by Pandarix** [comment]
Update with the fix is out now!

[![Modrinth](https://img.shields.io/modrinth/v/zCh7omyG?style=flat&logo=modrinth&logoColor=forestgreen&label=newest%3A&labelColor=black&color=forestgreen)](https://modrinth.com/mod/better-archeology)
[![CurseForge](https://img.shields.io/curseforge/v/835687?style=flat&logo=curseforge&logoColor=orangered&label=newest%3A&labelColor=black&color=orangered)](https://www.curseforge.com/minecraft/mc-mods/better-archeology)
