### ISSUE TITLE
Brushing self placed blocks of fossiliferous dirt don't drop any Items and just turns to normal dirt.

### ISSUE THREAD

**Issue by AndySpacesoul** [Pandarix/BetterArcheology#94]
I think it is because it has no indication to which archeology site it belongs.
What can I input into the {} of the command line
/give [playername] betterarcheology:fossiliferous_dirt{}

**Comment by Pandarix** [comment]
Jep, that is correct. The mod uses `processor_list`s to assign the right LootTable at runtime.
That way I don't have to redo all the structures when I want to change the LootTables.

I am unsure if it is possible to do that with `/give` since that data is written into the BlockEntity but here's a template for a `/setblock` command:

```
/setblock x y z betterarcheology:fossiliferous_dirt{LootTable:"location"}
```

---

For `location`, you can use every sort of `loot_table`. BetterArcheology has these paths, if you want to use the built-in ones:
<details>
<summary>Fossiliferous Dirt</summary>
<br>

```
betterarcheology:archeology/fossiliferous_dirt_chicken
```
```
betterarcheology:archeology/fossiliferous_dirt_creeper
```
```
betterarcheology:archeology/fossiliferous_dirt_jungle
```
```
betterarcheology:archeology/fossiliferous_dirt_sheep
```
```
betterarcheology:archeology/fossiliferous_dirt_villager
```
```
betterarcheology:archeology/fossiliferous_dirt_wolf
```
```
betterarcheology:archeology/fossiliferous_dirt_guardian
```
</details>

<details>
<summary>Suspicious Blocks</summary>
<br>

```
betterarcheology:archeology/desert_sand
```
```
betterarcheology:archeology/plains_gravel
```
```
betterarcheology:archeology/taiga_dirt
```
```
betterarcheology:archeology/mesa_red_sand
```
</details>

**Comment by AndySpacesoul** [comment]
Thanks that was very helpful.
The /give command seem not to work but the /place command works perfectly fine.
